import * as React from "react";

interface EmailTemplateProps {
  fullName: string;
  email: string;
  phone: string;
  projectDetails: string;
}

export function EmailTemplate({
  fullName,
  email,
  phone,
  projectDetails,
}: EmailTemplateProps) {
  return (
    <div
      style={{
        fontFamily:
          'system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial',
        color: "#111827",
      }}
    >
      <h1 style={{ fontSize: 20, marginBottom: 8 }}>New project inquiry</h1>

      <p style={{ margin: 0 }}>
        You have received a new project inquiry with the following details:
      </p>

      <table
        style={{ width: "100%", borderCollapse: "collapse", marginTop: 12 }}
      >
        <tbody>
          <tr>
            <td style={{ padding: "6px 8px", fontWeight: 600, width: 160 }}>
              Full name
            </td>
            <td style={{ padding: "6px 8px" }}>{fullName}</td>
          </tr>
          <tr style={{ background: "#f9fafb" }}>
            <td style={{ padding: "6px 8px", fontWeight: 600 }}>Email</td>
            <td style={{ padding: "6px 8px" }}>{email}</td>
          </tr>
          <tr>
            <td style={{ padding: "6px 8px", fontWeight: 600 }}>Phone</td>
            <td style={{ padding: "6px 8px" }}>{phone}</td>
          </tr>
          <tr style={{ background: "#f9fafb" }}>
            <td
              style={{
                padding: "6px 8px",
                fontWeight: 600,
                verticalAlign: "top",
              }}
            >
              Project details
            </td>
            <td style={{ padding: "6px 8px", whiteSpace: "pre-wrap" }}>
              {projectDetails}
            </td>
          </tr>
        </tbody>
      </table>

      <p style={{ marginTop: 14 }}>
        Reply to the customer at <a href={`mailto:${email}`}>{email}</a> or call{" "}
        {phone}.
      </p>

      <p style={{ color: "#6b7280", fontSize: 13, marginTop: 18 }}>
        This message was generated by your website contact form.
      </p>
    </div>
  );
}
